Create integrations.md
opencost/opencost-website pull request #110
Opened 2023-05-08 19:39 UTC by bstuder99

Responds to https://github.com/kubecost/docs/issues/630 to create a list of supported OpenCost integrations
Relevant integration/config docs are linked where they already exist. We can work on developing specific integration guides for everything else over time

2023-05-09 07:44 UTC, mattray requested changes

2023-05-09 07:44 UTC, mattray commented on docs/integrations.md
> +* [AWS](https://github.com/opencost/opencost-website/blob/main/docs/AWS.md)
Could we change this to https://www.opencost.io/docs/AWS

2023-05-09 07:44 UTC, mattray commented on docs/integrations.md
> +* [Azure](https://github.com/opencost/opencost-website/blob/main/docs/azure-opencost.md)
Could we change this to https://www.opencost.io/docs/azure-opencost

2023-05-09 14:15 UTC, bstuder99 commented
I'm pretty sure I grabbed every URL from the frontend, not GH. In certain cases (in Kubecost docs), these links direct you to the platform you are currently browsing. ie, browsing docs in GH will link you to more GH docs, but browsing docs in the frontend links you to other frontend docs.

2023-05-10 06:42 UTC, mattray commented
The Vercel preview shows the links going to GitHub, maybe the Kubecost docs work differently when rendered.
https://opencost-website-git-bstuder99-patch-3-kubecost.vercel.app/docs/integrations

2023-05-10 13:30 UTC, bstuder99 commented
Okay, everything's been manually corrected

2023-05-10 20:34 UTC, mattray approved these changes

2023-05-10 20:34 UTC, mattray commented
Thanks!

2023-05-10 20:34 UTC, merged